---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.sleuth.io
  resources:
  - deploymentrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.sleuth.io
  resources:
  - deploymentrules/finalizers
  verbs:
  - update
- apiGroups:
  - core.sleuth.io
  resources:
  - deploymentrules/status
  verbs:
  - get
  - patch
  - update
