apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
spec:
  selector:
    matchLabels:
      app: test-123
  template:
    metadata:
      name: test
      labels:
        app: test-123
    spec:
      containers:
        - name: test
          image: nginxdemos/hello
