apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: default
  labels:
    sleuth-label: select-me
    app: hello-world
    sha: 111a
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      name: test
      labels:
        app: hello-world
    spec:
      containers:
        - name: test
          image: nginxdemos/hello