name: "CI"
on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: CI - Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0 <1.18.0'
      - name: Format
        run: files=$(gofmt -s -l .); if [ $(echo -n "${files}" | wc -c) -gt 0 ]; then echo $files && exit 1; fi
      - name: Vet and Test
        run: make test

  build:
    name: CI - Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0 <1.18.0'
      - name: Build
        run: make build-ci